// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: pb/shortlink.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=LongUrl,proto3" json:"LongUrl,omitempty"`
}

func (x *ConvertReq) Reset() {
	*x = ConvertReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shortlink_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertReq) ProtoMessage() {}

func (x *ConvertReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortlink_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertReq.ProtoReflect.Descriptor instead.
func (*ConvertReq) Descriptor() ([]byte, []int) {
	return file_pb_shortlink_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertReq) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type ConvertResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=ShortUrl,proto3" json:"ShortUrl,omitempty"`
}

func (x *ConvertResp) Reset() {
	*x = ConvertResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shortlink_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResp) ProtoMessage() {}

func (x *ConvertResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shortlink_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResp.ProtoReflect.Descriptor instead.
func (*ConvertResp) Descriptor() ([]byte, []int) {
	return file_pb_shortlink_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertResp) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

var File_pb_shortlink_proto protoreflect.FileDescriptor

var file_pb_shortlink_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x26, 0x0a, 0x0a, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x6e, 0x67, 0x55,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x6e, 0x67, 0x55, 0x72,
	0x6c, 0x22, 0x29, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x32, 0x3e, 0x0a, 0x0e,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_shortlink_proto_rawDescOnce sync.Once
	file_pb_shortlink_proto_rawDescData = file_pb_shortlink_proto_rawDesc
)

func file_pb_shortlink_proto_rawDescGZIP() []byte {
	file_pb_shortlink_proto_rawDescOnce.Do(func() {
		file_pb_shortlink_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_shortlink_proto_rawDescData)
	})
	return file_pb_shortlink_proto_rawDescData
}

var file_pb_shortlink_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_shortlink_proto_goTypes = []interface{}{
	(*ConvertReq)(nil),  // 0: rpc.ConvertReq
	(*ConvertResp)(nil), // 1: rpc.ConvertResp
}
var file_pb_shortlink_proto_depIdxs = []int32{
	0, // 0: rpc.ConvertService.convert:input_type -> rpc.ConvertReq
	1, // 1: rpc.ConvertService.convert:output_type -> rpc.ConvertResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_shortlink_proto_init() }
func file_pb_shortlink_proto_init() {
	if File_pb_shortlink_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_shortlink_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shortlink_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_shortlink_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_shortlink_proto_goTypes,
		DependencyIndexes: file_pb_shortlink_proto_depIdxs,
		MessageInfos:      file_pb_shortlink_proto_msgTypes,
	}.Build()
	File_pb_shortlink_proto = out.File
	file_pb_shortlink_proto_rawDesc = nil
	file_pb_shortlink_proto_goTypes = nil
	file_pb_shortlink_proto_depIdxs = nil
}
